image: openjdk:11-jdk-slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone #makes sure that runner clone fresh repository.
  GIT_DEPTH: 1 #clone repository for last commit. known as shallow clone.

stages:
  - build
  - test

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  tags:
    - grad
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  tags:
    - grad
  script:
    - ./gradlew check

after_script:
  - echo "End CI"