spring:
  profiles:
    active: dev
    include:  application-${spring.profiles.active}.yml
logging:
#  level:
#    org.springframework: ERROR
#    com.assessme: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: logs/applogs.log